version: 2
jobs:
  build:
    working_directory: ~/p2002
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: ubuntu:xenial
    steps:
      - run:
          name: Install Deps
          command: 'apt-get update -qq && apt-get install -y -qq gcc-4.8 g++-4.8 libmysqlclient-dev libperl-dev libboost-dev liblua5.1-0-dev zlib1g-dev uuid-dev libssl-dev build-essential make cmake git-core unzip curl'
      - run:
          name: Install Protobuf
          command: 'mkdir temp && cd temp && curl -OL https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf/+files/libprotobuf-dev_3.1.0-0ubuntu1~maarten0_amd64.deb && curl -OL https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf/+files/protobuf-compiler_3.1.0-0ubuntu1~maarten0_amd64.deb &&curl -OL https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf/+files/libprotobuf-lite10_3.1.0-0ubuntu1~maarten0_amd64.deb && curl -OL https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf/+files/libprotoc10_3.1.0-0ubuntu1~maarten0_amd64.deb && curl -OL https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf/+files/libprotoc-dev_3.1.0-0ubuntu1~maarten0_amd64.deb && DEBIAN_FRONTEND=noninteractive dpkg -R --install . && cd .. && rm -rf temp'
      - run:
          name: Check Protobuf Version
          command: 'protoc --version'
      - checkout
      - run:
          name: CMake Env
          command: 'cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=ON -DEQEMU_BUILD_LOGIN=ON'
      - run:
          name: Build Source
          command: 'make -j 2'
      - run:
          name: Test
          command: './bin/tests'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
                - nats3
